version: "3"

services:
  front:
    image: ${REPOSITORY_URL}/${IMAGE_FRONT}:${APP_VERSION:-latest}
    ports:
      - 3000:3000
    environment:
      - HOST_URL=${HOST_URL}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - BACKEND_URL=${BACKEND_URL}

    logging:
      driver: awslogs
      options:
        awslogs-group: ${AWS_FRONT_LOGS_GROUP}
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: front
